backend:
  name: git-gateway
  branch: master

media_folder: static/img
public_folder: /img

collections:
  - name: "report"
    label: "Report"
    folder: "src/pages/report"
    create: true
    slug: "{{slug}}"
    fields:
      - {label: "Template Key", name: "templateKey", widget: "hidden", default: "report"}
      - {label: "Title", name: "title", widget: text}
      - {label: "Versant Logo", name: "versantlogo", widget: image}
      - {label: "Partner Logo", name: "partnerlogo", widget: image}
      - {label: "Pearson Image", name: "pearsonlogo", widget: image}
      # - {label: "Body", name: "body", widget: "markdown"}
